version: "3.2"
services:

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
    networks:
      - mynet

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/  
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - mynet

  backend:    
    restart: always
    build:
      context: ./
    volumes:
      - .:/src
    depends_on:
      - 'rabbitmq'
      - mongodb
    environment:
      PORT: 4000
      AMQP_URL: amqp://quest:quest@rabbitmq:5672
      MONGODB: mongodb://mongodb:27017/mydb
      ACCESS_TOKEN_SECRET: tokenjwtlalalal
    ports:
        - 4000:4000
    networks:
      - mynet

networks:
  mynet:
    driver: bridge      
