version: "3.2"
services:

  minio:
    image: bitnami/minio:latest
    ports:
      - '127.0.0.1:9001:9001'
      - '127.0.0.1:9000:9000'

    environment:
      MINIO_ROOT_USER: myminiouser
      MINIO_ROOT_PASSWORD: myminiopassword
      MINIO_SERVER_HOST: localhost
      MINIO_SCHEME: http
      MINIO_API_CORS_ALLOW_ORIGIN: '*'
    networks:
    - mynet  

  mc: 
    image: minio/mc
    container_name: mc
    depends_on: 
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --api s3v4 minio http://minio:9000/ myminiouser myminiopassword;
      /usr/bin/mc rm -r --force minio/first-bucket;
      /usr/bin/mc mb -p minio/first-bucket;
      /usr/bin/mc admin policy set public minio/first-bucket;
      /usr/bin/mc admin trace minio -a --debug;
      "
    networks:
      - mynet 

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
    networks:
      - mynet

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

    networks:
      - mynet

  backend:
    image: rede-social-ludmylla
    restart: always
    build:
      context: ./
    volumes:
      - .:/src
    depends_on:
      - rabbitmq
      - mongodb
      - minio
    environment:
      PORT: 3000
      MONGODB: mongodb://mongodb:27017/mydb
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      ACCESS_TOKEN_SECRET: 2634d3209b728707236765918773edda
      BUCKET_HOST: http://localhost:9000/
      BUCKET_ENDPOINT: http://minio:9000/
      BUCKET_ACCESS_KEY: myminiouser
      BUCKET_SECRET_KEY: myminiopassword
    ports:
        - 3000:3000
    networks:
      - mynet

networks:
  mynet:
    driver: bridge      
